name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    container: nixos/nix:2.24.11
    steps:
      - name: Create os-release file
        run: echo "ID=nixos" > /etc/os-release
      - uses: actions/checkout@v4
      - name: Build
        run: |
          nix-shell shell.nix
          mkdir build && cd build
          cmake ..
          cmake --build .
      - name: Test
        run: ctest
