name: build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    container: archlinux:latest
    strategy:
      fail-fast: true
      matrix:
        compiler-cxx: ['g++', 'clang++']
    steps:
      - uses: actions/checkout@v3
      - name: Install dependecies
        run: |
          pacman -Syu --noconfirm --quiet cmake asio gcc clang ninja pkgconf git
      - name: build with cmake
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_TESTS=ON -G "Ninja" -D CMAKE_CXX_COMPILER=${{matrix.compiler-cxx}}
          cmake --build . 
          ctest